config/routes.rb
Rails.application.routes.draw do
  get 'guesses/create'
  resources :guesses, only: [:create]
  resources :post_attachments
  resources :posts

  root :to=>"posts#index"

end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :post_attachment
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :post_attachments
    accepts_nested_attributes_for :post_attachments
    # Nested attributes allow you to save attributes
    # on assoicated records through the parent
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
    mount_uploader :avatar, AvatarUploader
    belongs_to :post 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  
  def create
    @guess = Guess.new(guess_params)

    respond_to do |format|
      if @guess.save
        format.html { redirect_to @guess.post_attachment.post, notice: 'Post attachment was successfully created.' }
        format.json { render json: @guess, status: :created}
      else
        format.html { render :new }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def guess_params
    params.require(:guess).permit(:post_attachment_id, :index, :url)
  end

end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_attachment }
      else
        format.html { render :edit }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :avatar)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_attachments = @post.post_attachments.all
    @guess = Guess.new post_attachment: @post.post_attachments.first, index: 1
    @guesses = Guess.all
    
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        params[:post_attachments]['avatar'].each do |a|
          @post_attachment = @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      #   format.json { render :show, status: :created, location: @post }
      else
        format.html { render action: 'new' }
      #   format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, post_attachments_atrributes:[:id, :post_id, :avatar])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/guesses/create.html.erb
<h1>Guesses#create</h1>
<p>Find me in app/views/guesses/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post_attachments/_form.html.erb
<%= form_for(@post_attachment) do |f| %>
  <% if @post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% @post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Post attachment', new_post_attachment_path %>
<%= link_to 'Home', posts_path %>

app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @post_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

 <%= f.fields_for :post_attachments do |p| %>
  <div class="field">
    <%= p.label :avatar %><br>
    <%= p.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]", :required => 'required' %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  <button type="button" id="play">Play</button>
  <span id="countdown" style="font-weight: bold;"></span>
  <div id="showImage"></div>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

  <table style="width:100%">
  <tr>
    <th>Timer</th>
    <th>Image</th>
  </tr>
  <tr>
    <td class='index'><br>
  </tr>
  <tr>
    <td class='img'><br>
  </tr>
    
  </table>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<script type = "text/javascript">

  <% ary10 = Array.new %>
   <% @post.post_attachments.each do |post_attachment| %>
    <% ary10.push(post_attachment) %>
  <% end %>

  <% @post.post_attachments.each do |post_attachment| %>
    <% while ary10.length < 10 %>
      <% ary10.push(post_attachment) %>
    <% end  %>
  <% end %>

  <% ary10.shuffle! %>

  var attachments = <%= ary10.to_json.html_safe %>;
    let currentImg = document.getElementById("showImage");
    let count = 9;
    let currentAttachment = attachments[count];
  
  function countdown() {
    function sendData(){

      return fetch('/guesses.json', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json'},
        body: JSON.stringify({
          guess: {
            post_attachment_id: currentAttachment.id,
            index: count
          }
        })
      })
      .then(function(response){ return response.json() })
  }
    let timerId = setInterval(function() {

      count--;
      let counter = count + 2;
      document.getElementById("countdown").innerHTML = counter;
    
      if(count == -1){
        count = 9;
      }
      currentAttachment = attachments[count];
      currentImg.innerHTML=`<img src=${currentAttachment.avatar.url} height=300 width=350>`;

    }, 1000);

    document.getElementById("play").addEventListener("click", event => {
      sendData().then(response => {
      console.log(response)
      let imgNode = document.createElement('td')
      let srcNode = document.createTextNode(currentAttachment.avatar.url)
      imgNode.appendChild(srcNode)
      document.getElementsByClassName("img")[0].appendChild(imgNode).innerHTML=`<img src=${currentAttachment.avatar.url} height=100 width=100>`
      let indexNode = document.createElement('td')
      let textnode = document.createTextNode(response.index)
      indexNode.appendChild(textnode)
      document.getElementsByClassName("index")[0].appendChild(indexNode)
      console.log(currentAttachment.avatar.url)
      }) 
    });
  }
  
  countdown();
  
</script>